name: Deploy to Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
        chmod 600 /tmp/id_rsa

    - name: Debug SSH connection
      run: |
        ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

    - name: Sync files to server
      run: |
        rsync -avz -e "ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/pterodactyl

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /var/www/pterodactyl
          php artisan migrate --force
          composer require laravel/socialite
          composer require socialiteproviders/discord
          yarn add lucide-react
          yarn add esbuild-loader
          yarn add monaco-editor @monaco-editor/react
          yarn add sanitize-html@2.7.3 @types/sanitize-html@2.6.2
          yarn build:production
          php artisan optimize:clear
          php artisan view:clear && php artisan cache:clear && php artisan route:clear && php artisan migrate --force && chown -R www-data:www-data *

